<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Zurari.Controls\Zurari.Controls.csproj" />
    <ProjectReference Include="..\Zurari.Runtime\Zurari.Runtime.csproj" />
    <ProjectReference Include="..\Zurari.Shell\Zurari.Shell.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Zurari.App.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
